(rule invHandicap (let (maxHandicap (defaultValue systemMaxHandicap 9)) 
		(if (greaterthan game_Handicap maxHandicap) GameStateRejected GameStateUnknown)))
(rule notReady (if (isnull game_GAMEQUALITYTRAILING) GameStateNotReady GameStateUnknown))
(rule afterDate (if (lessthan game_datePlayed (defaultValue systemPreDateCutoff "2008-01-01")) GameStateRejected GameStateUnknown))
(rule processTill (if (and (not (isnull systemPostDateCutoff)) (greaterthanequal game_datePlayed systemPostDateCutoff)) GameStateNotReady GameStateUnknown))
(rule threshold (let (thresholdLimit (defaultValue systemQualityThreshold ".05"))
                            (if (and (lessthanequal (threshold game_GAMEPROBABILITY) thresholdLimit) 
                                     (lessthanequal (threshold game_GAMETRAILINGPROBABILITY) thresholdLimit))
                                GameStateRejected GameStateValid)))